ALTER TABLE users
  ADD COLUMN IF NOT EXISTS otp_code TEXT DEFAULT NULL;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS otp_expires_at TIMESTAMP DEFAULT NULL;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN DEFAULT FALSE;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS otp_verified_at TIMESTAMP DEFAULT NULL;
